#!/bin/bash

mkdir -p RSEM_Results

for sample in C1_311 C2_212 C2_312 C3_212 LD2_212 LD2_312 LD3_212 LD3_312
do
    echo "Processing sample: $sample"
    
    rsem-calculate-expression --paired-end \
        --bowtie2 \
        --strandedness reverse \
        --estimate-rspd --calc-ci \
        --output-genome-bam \
        --append-names --keep-intermediate-files \
        /home/s2451842/HAoECs_raw_fastq/${sample}_1.fq.gz \
        /home/s2451842/HAoECs_raw_fastq/${sample}_2.fq.gz \
        RSEM_Reference/Homo_sapiens_GRCh38 \
        RSEM_Results/${sample}
    
    echo "Finished processing: $sample"
done
